apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  server: IP
  path: /nfsdir
  readOnly: "false"
allowVolumeExpansion: true

reclaimPolicy: Retain

volumeBindingMode: Immediate